const _ACTIONS = {
  LIST_NETWORKS: 'LIST_NETWORKS',
  LIST_NETWORKS_SUCCESS: 'LIST_NETWORKS_SUCCESS',
  LIST_NETWORKS_FAIL: 'LIST_NETWORKS_FAIL',
  DELETE_NETWORK: 'DELETE_NETWORK',
  DELETE_NETWORK_SUCCESS: 'DELETE_NETWORK_SUCCESS',
  DELETE_NETWORK_FAIL: 'DELETE_NETWORK_FAIL',
};

Object.keys(_ACTIONS).forEach((key) => {
  _ACTIONS[key] = 'networks/' + _ACTIONS[key];
});
export const ACTIONS = _ACTIONS;
