const _ACTIONS = {
  LOAD_LOGS: 'LOAD_LOGS',
  LOAD_LOGS_SUCCESS: 'LOAD_LOGS_SUCCESS',
  LOAD_LOGS_FAIL: 'LOAD_LOGS_FAIL',
  CREATE: 'CREATE',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  CREATE_FAIL: 'CREATE_FAIL',
  START: 'START',
  START_SUCCESS: 'START_SUCCESS',
  START_FAIL: 'START_FAIL',
  STOP: 'STOP',
  STOP_SUCCESS: 'STOP_SUCCESS',
  STOP_FAIL: 'STOP_FAIL',
  RESTART: 'RESTART',
  RESTART_SUCCESS: 'RESTART_SUCCESS',
  RESTART_FAIL: 'RESTART_FAIL',
  REMOVE: 'REMOVE',
  REMOVE_SUCCESS: 'REMOVE_SUCCESS',
  REMOVE_FAIL: 'REMOVE_FAIL',
  SCALE: 'SCALE',
  SCALE_SUCCESS: 'SCALE_SUCCESS',
  SCALE_FAIL: 'SCALE_FAIL'
};

Object.keys(_ACTIONS).forEach((key) => {
  _ACTIONS[key] = 'containers/' + _ACTIONS[key];
});
export const ACTIONS = _ACTIONS;
