const _ACTIONS = {
  GET_ROLES: 'GET_ROLES',
  GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
  GET_ROLES_FAIL: 'GET_ROLES_FAIL',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAIL: 'GET_CURRENT_USER_FAIL',
  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAIL: 'GET_USERS_FAIL',
  DELETE_USER: 'DELETE_USER',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAIL: 'DELETE_USER_FAIL',
  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAIL: 'GET_USER_FAIL',
  SET_USER: 'SET_USER',
  SET_USER_SUCCESS: 'SET_USER_SUCCESS',
  SET_USER_FAIL: 'SET_USER_FAIL',
  GET_USER_ROLES: 'GET_USER_ROLES',
  GET_USER_ROLES_SUCCESS: 'GET_USER_ROLES_SUCCESS',
  GET_USER_ROLES_FAIL: 'GET_USER_ROLES_FAIL',
  DELETE_USER_ROLE: 'DELETE_USER_ROLE',
  DELETE_USER_ROLE_SUCCESS: 'DELETE_USER_ROLE_SUCCESS',
  DELETE_USER_ROLE_FAIL: 'DELETE_USER_ROLE_FAIL',
  ADD_USER_ROLE: 'ADD_USER_ROLE',
  ADD_USER_ROLE_SUCCESS: 'ADD_USER_ROLE_SUCCESS',
  ADD_USER_ROLE_FAIL: 'ADD_USER_ROLE_FAIL'
};

Object.keys(_ACTIONS).forEach((key) => {
  _ACTIONS[key] = 'users/' + _ACTIONS[key];
});
export const ACTIONS = _ACTIONS;
