const _ACTIONS = {
  LOAD_SERVICES: 'LOAD_SERVICES',
  LOAD_SERVICES_SUCCESS: 'LOAD_SERVICES_SUCCESS',
  LOAD_SERVICES_FAIL: 'LOAD_SERVICES_FAIL',
  CREATE_SERVICE: 'CREATE_SERVICE',
  CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
  CREATE_SERVICE_FAIL: 'CREATE_SERVICE_FAIL',
  DELETE_SERVICE: 'DELETE_SERVICE',
  DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
  DELETE_SERVICE_FAIL: 'DELETE_SERVICE_FAIL',
  SCALE_SERVICE: 'SCALE_SERVICE',
  SCALE_SERVICE_SUCCESS: 'SCALE_SERVICE_SUCCESS',
  SCALE_SERVICE_FAIL: 'SCALE_SERVICE_FAIL',
  GET_SERVICE: 'GET_SERVICE',
  GET_SERVICE_SUCCESS: 'GET_SERVICE_SUCCESS',
  GET_SERVICE_FAIL: 'GET_SERVICE_FAIL',
};

Object.keys(_ACTIONS).forEach((key) => {
  _ACTIONS[key] = 'services/' + _ACTIONS[key];
});
export const ACTIONS = _ACTIONS;
