const _ACTIONS = {
  ADD_REGISTER: 'ADD_REGISTER',
  ADD_REGISTER_SUCCESS: 'ADD_REGISTER_SUCCESS',
  ADD_REGISTER_FAIL: 'ADD_REGISTER_FAIL',
  LOAD_REGISTRIES: 'LOAD_REGISTRIES',
  LOAD_REGISTRIES_SUCCESS: 'LOAD_REGISTRIES_SUCCESS',
  LOAD_REGISTRIES_FAIL: 'LOAD_REGISTRIES_FAIL'
};

Object.keys(_ACTIONS).forEach((key) => {
  _ACTIONS[key] = 'registries/' + _ACTIONS[key];
});
export const ACTIONS = _ACTIONS;
